"""Tests for the Telegram inbound Company OS hard-gate route contract.

When a Telegram user message triggers a route to a workflow with
``hard_confirmation_required`` gates, the route prefix injected into
the agent prompt MUST:

1. Include the phrase ``HARD_GATE_REQUIRED`` so the agent cannot miss it.
2. Surface the pending ``approval_id`` (when one was generated by the
   control-envelope) so the user sees it in the visible line.
3. List every gate the workflow enforces.
4. Be reachable in pure unit form (i.e. the agent prompt construction
   does not depend on the live gateway).
"""

from types import SimpleNamespace

import pytest

pytest.importorskip("telegram", reason="python-telegram-bot not installed")


def _make_source(platform: str = "telegram", chat_id: str = "123") -> SimpleNamespace:
    return SimpleNamespace(platform=SimpleNamespace(value=platform), chat_id=chat_id)


HARD_GATE_ROUTE = (
    "control_version: 2\n"
    "run_id: run-20260624-test\n"
    "mcp_profile_id: ops_guarded\n"
    "task:\n"
    "  task_id: task-20260624-test\n"
    "approval:\n"
    "  approval_id: approval-20260624-test\n"
    "route:\n"
    "  domain_id: money.services\n"
    "  workflow_id: service_delivery_loop\n"
    "  review_gates:\n"
    "  - external_send\n"
    "  - price_commitment\n"
    "  - investment_action\n"
    "  gate_plan:\n"
    "    hard_confirmation_required: true\n"
)

SOFT_ROUTE = (
    "control_version: 1\n"
    "task:\n"
    "  task_id: task-20260624-soft\n"
    "approval: {}\n"
    "route:\n"
    "  domain_id: creative.media\n"
    "  workflow_id: creative_production_loop\n"
    "  review_gates:\n"
    "  - public_content_review\n"
    "  gate_plan:\n"
    "    hard_confirmation_required: false\n"
)


def test_route_prefix_contains_hard_gate_marker():
    from gateway.run import GatewayRunner
    runner = GatewayRunner.__new__(GatewayRunner)
    injected = runner._build_company_os_route_injection(
        "test request", _make_source(), route_output=HARD_GATE_ROUTE,
    )
    assert "HARD_GATE_REQUIRED" in injected
    assert "approval-20260624-test" in injected
    assert "external_send" in injected
    assert "money.services" in injected
    assert "service_delivery_loop" in injected
    assert "hard_gate=required" in injected


def test_route_prefix_omits_hard_gate_marker_when_soft():
    from gateway.run import GatewayRunner
    runner = GatewayRunner.__new__(GatewayRunner)
    injected = runner._build_company_os_route_injection(
        "test", _make_source(), route_output=SOFT_ROUTE,
    )
    assert "HARD_GATE_REQUIRED: Do not perform" not in injected
    assert "creative.media" in injected
    assert "public_content_review" in injected
    assert "hard_gate=required" not in injected


def test_should_route_ignores_short_casual_messages():
    from gateway.run import GatewayRunner
    runner = GatewayRunner.__new__(GatewayRunner)
    assert not runner._should_company_os_route_message("你好", _make_source())
    assert not runner._should_company_os_route_message("hi", _make_source())
    assert runner._should_company_os_route_message("帮我研判下拓维信息", _make_source())


def test_route_prefix_visible_line_includes_approval_id():
    """The visible line the agent MUST echo to the user surfaces the
    pending approval_id so the user can immediately act on it."""
    from gateway.run import GatewayRunner
    runner = GatewayRunner.__new__(GatewayRunner)
    injected = runner._build_company_os_route_injection(
        "test", _make_source(), route_output=HARD_GATE_ROUTE,
    )
    # Find the visible line block (between [Company OS route injection] and Raw local route result)
    start = injected.index("[Company OS route injection]")
    end = injected.index("Raw local route result:")
    visible_block = injected[start:end]
    assert "approval=approval-20260624-test" in visible_block
    assert "domain=money.services" in visible_block
    assert "workflow=service_delivery_loop" in visible_block


def test_route_payload_exposes_approval_context():
    from gateway.run import GatewayRunner
    runner = GatewayRunner.__new__(GatewayRunner)

    payload = runner._build_company_os_route_injection_payload(
        "test", _make_source(), route_output=HARD_GATE_ROUTE,
    )

    assert payload["approval_id"] == "approval-20260624-test"
    assert payload["hard_gate_required"] is True
    assert payload["run_id"] == "run-20260624-test"
    assert payload["domain_id"] == "money.services"
    assert payload["mcp_profile_id"] == "ops_guarded"
    assert "HARD_GATE_REQUIRED" in payload["message_text"]
